# Generated by Django 3.2 on 2022-12-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
